### ISSUE TITLE
Ruby 3.x compatibility

### ISSUE THREAD

**Issue by n-rodriguez** [codecov/codecov-ruby#121]
Ruby 3 is out and codecov-ruby is not compatible with it :

it fallbacks to `codecov 0.2.12` :

`Using codecov 0.2.12 (was 0.2.15)`

```diff
-    codecov (0.2.15)
-      simplecov (>= 0.15, < 0.21)
+    codecov (0.2.12)
+      json
+      simplecov
```

Because of https://github.com/codecov/codecov-ruby/commit/b8fad69be0a49b9be521088ed01c9ea9b60d2c83#diff-04cb1f7276546201ae5ccb1c2165c2b6c9ed202c6e6d7dd4ea803e32386a7dc2

**Comment by AlexWayfer** [comment]
> Ruby 3 is out and codecov-ruby is not compatible with it :
> 
> it fallbacks to `codecov 0.2.12` :
> 
> `Using codecov 0.2.12 (was 0.2.15)`
> 
> ```diff
> -    codecov (0.2.15)
> -      simplecov (>= 0.15, < 0.21)
> +    codecov (0.2.12)
> +      json
> +      simplecov
> ```
> 
> Because of [b8fad69#diff-04cb1f7276546201ae5ccb1c2165c2b6c9ed202c6e6d7dd4ea803e32386a7dc2](https://github.com/codecov/codecov-ruby/commit/b8fad69be0a49b9be521088ed01c9ea9b60d2c83#diff-04cb1f7276546201ae5ccb1c2165c2b6c9ed202c6e6d7dd4ea803e32386a7dc2)

And what does it have to do with Ruby 3?

**Comment by n-rodriguez** [comment]
> And what does it have to do with Ruby 3?

It's painfuly obvious you dont know how your tools work...

**Comment by AlexWayfer** [comment]
> > And what does it have to do with Ruby 3?
> 
> It's painfuly obvious you dont know how your tools work...

You didn't answered. You've wrote "codecov is not compatible with Ruby 3" and attached `Gemfile.lock` diff without Ruby 3 information, specific, at least clarification. 

Oh, I got it: you meant this diff as result, not as reason. Sorry. OK.

**Comment by AlexWayfer** [comment]
> @n-rodriguez closed this 10 hours ago

Why? I agreed with the issue and apologized. It's still here, and though changes in your PR was dangerous (step back), I've suggested more safe changes for resolution this issue. There is a button to accept them and the PR can be merged.

**Comment by n-rodriguez** [comment]
Someone else will do the job better than me.

**Comment by thomasrockhu** [comment]
Thanks all, this will be released shortly and fixed via https://github.com/codecov/codecov-ruby/pull/124
