### ISSUE TITLE
Using flags

### ISSUE THREAD

**Issue by Nerian** [codecov/codecov-ruby#139]
Hi,

https://docs.codecov.io/docs/about-the-codecov-bash-uploader#arguments

When using the bash it would be something like this:

bash <(curl -s https://codecov.io/bash) -F flag1

How can I set the flags when using codecov-ruby?

Thanks.

**Comment by thomasrockhu** [comment]
@Nerian this is unfortunately not possible with the Ruby uploader. I'll let the product team know

**Comment by Nerian** [comment]
Hi,

It is possible, but not documented. I just needed to use the env variables:

https://github.com/codecov/codecov-ruby/blob/master/lib/codecov/uploader.rb#L130

I suggest documenting it in the readme.
