### ISSUE TITLE
Heroku CI not supported

### ISSUE THREAD

**Issue by reggaemuffin** [codecov/codecov-ruby#21]
Heroku CI is in Beta right now. Sadly it does not test inside a git repo, so you have to parse their env variables: https://devcenter.heroku.com/articles/heroku-ci#environment-variables

Any possibilty to add support?

**Comment by stevepeak** [comment]
Hey @Kostronor Thank you for the issue 👍 

Do you know if `$ git` is available during the CI build? That can pull the correct commit information.

I'll add support to detect Heroku, but it appears there are only 2 default environment variables which does not really help.

**Comment by Kostronor** [comment]
It seems they do not have git on their CI system. But their system is in beta, so maybe you can still convince them to support it or give better ENV 😉

**Comment by stevepeak** [comment]
Ok. Hopefully they will add more environment variables and `git` support. Otherwise, it may be difficult to get the context of the upload.

**Comment by Kostronor** [comment]
# Feedback
We’re eager to hear about your experience (and help) with Heroku CI, so please send comments and questions to heroku-ci-feedback@heroku.com .

I've send them a feedback mail with a link to this issue.

**Comment by appleton** [comment]
👋  Hello, I'm on the Heroku CI team. This is definitely something we'd like to support, we've had a similar request for [codeclimate](https://github.com/codeclimate/ruby-test-reporter/issues/183) so I'd like to try and get a full set of information which anyone can make use of.

We can't easily give you git and a repository but we can most likely give you some environment variables with the information you need. Could you let me know what you'd need?

**Comment by stujo** [comment]
@stevepeak Sounds like Heroku CI is on board to help if we can give them the info they need, would love to get this working. Please let me know how I can help

**Comment by stevepeak** [comment]
@appleton my apologies on the delay. We should schedule a chat to discuss this integration process. Are there been any changes that I should be aware of? Thanks!

**Comment by appleton** [comment]
Hi @stevepeak I don't work at Herkou any more, I think you'd be best chatting with @joshwlewis or @raulb

**Comment by nfm** [comment]
Please close this issue, it has been resolved.
