### ISSUE TITLE
It seems .codecov.yml doesn't work and you can't place it anywhere in your repository

### ISSUE THREAD

**Issue by webgago** [codecov/codecov-ruby#24]
As per https://docs.codecov.io/docs/codecov-yaml#section-can-i-name-the-file-codecov-yml-
I tried to place my `.codecov.yml` under `.circleci/` i.e. `.circleci/.codecov.yml`.
It didn't work for me :( 
`.circleci/codecov.yml` didn't work too. So I had to rename it into `codecov.yml` which is working

**Comment by stevepeak** [comment]
Hey @webgago indeed the `.codecov.yml` path is not discovered properly by the Ruby uploader.
I can manually adjust your project while we work on improving this functionality.

**Comment by webgago** [comment]
Hey @stevepeak. Thanks for answering so quickly! 
That's fine. Could you please let me know when you fix this functionality.
Thanks!

**Comment by gdomingu** [comment]
Any update on this? Would like to add config using a `codecov.yml` file.

**Comment by thomasrockhu** [comment]
`codecov.yml` or `.codecov.yml` must be located in the root, `.github/` or `dev/` folders.
