### ISSUE TITLE
GitLab CI variable names have changed

### ISSUE THREAD

**Issue by nfm** [codecov/codecov-ruby#25]
GitLab renamed some of their CI variables in GitLab Runner v9: https://docs.gitlab.com/ce/ci/variables/README.html#9-0-renaming

As a result, we get the following error at the end of our test suite:

```sh
Formatter SimpleCov::Formatter::Codecov failed with NoMethodError: undefined method `split' for nil:NilClass (/builds/usabilityhub/app/vendor/bundle/ruby/2.3.0/gems/codecov-0.1.10/lib/codecov.rb:181:in `format')
```

**Comment by reedlaw** [comment]
Never mind, I found out all I needed to do was update my project's gems. I'm new to gitlab and wasn't sure where the installed gems were coming from.
