### ISSUE TITLE
VCR: Unhandled Request

### ISSUE THREAD

**Issue by justmatt** [codecov/codecov-ruby#6]
Related to #5 

![update_codecov_for_fix_ _inpharmd_inpharmd_ _codeship](https://cloud.githubusercontent.com/assets/426173/8756440/49bec902-2ca0-11e5-99ce-ad5a6e98105e.png)

**Comment by stevepeak** [comment]
I'm a novice at ruby, may I ask that you checkout the [source code](https://github.com/codecov/codecov-ruby/blob/master/lib/codecov.rb) to see if there is something needed to be fixed? Thanks!
