### ISSUE TITLE
Relative coverage 100% but change -0.01%

### ISSUE THREAD

**Issue by WillKoehrsen** [codecov/codecov-ruby#62]
On a recent PR, the <relative> coverage is 100%, but the change is -0.01%, which causes the PR to fail the coverage check. Why would this occur, and is there a "tolerance" setting where PRs that decrease the coverage by a percentage less than a specified tolerance are still approved? 

<img width="239" alt="Screen Shot 2020-06-08 at 09 08 19 CDT" src="https://user-images.githubusercontent.com/17484616/84040288-0e4f6a80-a968-11ea-9155-1ec8bf1aa3a6.png">

<img width="1058" alt="Screen Shot 2020-06-08 at 09 12 36 CDT" src="https://user-images.githubusercontent.com/17484616/84040537-5b334100-a968-11ea-9a50-b7d95dbf1b97.png">

**Comment by thomasrockhu** [comment]
Hi @WillKoehrsen, could you make a post on our [community boards](https://community.codecov.io)? 

You can use [threshold](https://docs.codecov.io/docs/commit-status#threshold) as a tolerance setting.
