### ISSUE TITLE
cannot load such file -- colorize

### ISSUE THREAD

**Issue by jpalumickas** [codecov/codecov-ruby#67]
New gem version raises an error:
```
cannot load such file -- colorize
```

I see new `colorize` gem was added. Dependency should be in `gemspec` file, not in `Gemfile`

**Comment by thomasrockhu** [comment]
@jpalumickas thanks for this, I released `0.1.19` which should fix the issue

**Comment by jpalumickas** [comment]
Thank you! working fine now!
