### ISSUE TITLE
HTTP 400 | Provided token is not a UUID

### ISSUE THREAD

**Issue by AlexWayfer** [codecov/codecov-ruby#77]
With 0.2.2:

https://github.com/AlexWayfer/sequel-enum_values/pull/36

https://cirrus-ci.com/task/5888498974588928?command=test#L98

![image](https://user-images.githubusercontent.com/6510020/87962746-5c57a200-cac0-11ea-8dbc-a7f9b0984324.png)

With 0.2.1:

https://github.com/AlexWayfer/sequel-enum_values/pull/37

https://cirrus-ci.com/task/5023444041465856?command=test#L98

![image](https://user-images.githubusercontent.com/6510020/87962812-76918000-cac0-11ea-8c6d-b64a89d4925b.png)

**Comment by AlexWayfer** [comment]
Sorry, `0.2.1` is broken too: https://cirrus-ci.com/task/5787749645025280?command=test#L98

![image](https://user-images.githubusercontent.com/6510020/87963698-ccb2f300-cac1-11ea-970a-28d68b57eb53.png)

So, maybe it's server-side error, or CI error. I don't know without logs and debug.

**Comment by thomasrockhu** [comment]
@AlexWayfer it looks like your token is not decrypted before sending it to Codecov, and thus we are unable to use it

**Comment by fkorotkov** [comment]
@AlexWayfer it's an issue with the depfu[bot]. Encrypted variables are not decrypted for bot users since [it's impossible to check what kind of permissions an app has for a particular repository](https://github.community/t/repository-permissions-for-github-app-fake-user/14287).

**Comment by AlexWayfer** [comment]
OK, sorry, my bad. I've tested it right now in two PRs.
