### ISSUE TITLE
Compatibility with GitHub Actions - timeout or connection error

### ISSUE THREAD

**Issue by aergonaut** [codecov/codecov-ruby#81]
I have been using Codecov for a long time with Travis CI, but recently I needed to make a switch to GitHub Actions as my CI provider.

I initially noticed that in my RSpec builds, Codecov was reporting that no CI provider was detected and so no API key was detected. I added my project's API key to my workflow and tried building again. This is the error I got:

```
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.2.3
x> No CI provider detected.
==> Appending file network
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io
    query: token=secret&flags&package=ruby-0.2.3&branch=master&commit=8fee707cb8c943a38d0e884b1d0c1590fb49a997
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.2.3&branch=master&commit=8fee707cb8c943a38d0e884b1d0c1590fb49a997
Timeout or connection error uploading coverage reports to Codecov. Retrying...
execution expired
Timeout or connection error uploading coverage reports to Codecov. Retrying...
execution expired
Timeout or connection error uploading coverage reports to Codecov. Out of retries.
execution expired
```

For my Jest tests, I am using https://github.com/codecov/codecov-action which seems to work great. Does codecov-action also work for Ruby coverage reports? Can this gem be updated to support GitHub Actions natively like Travis CI?

**Comment by thomasrockhu** [comment]
Yes, this should be updated in `0.2.5`

**Comment by aergonaut** [comment]
Thanks @thomasrockhu!
