### ISSUE TITLE
v0.2.4 cannot require 'version'

### ISSUE THREAD

**Issue by colindean** [codecov/codecov-ruby#84]
dependabot submitted https://github.com/Homebrew/homebrew-bundle/pull/765 and per test result in https://github.com/Homebrew/homebrew-bundle/pull/765/checks?check_run_id=956036259, it looks like c0db3b2ac9a50c9a55f964d57b5c06b3f71e25ad introduced a regression because of how it's pulling in the new version file.

```
An error occurred while loading ./spec/bundle/brew_dumper_spec.rb. - Did you mean?
                    rspec ./spec/bundle/whalebrew_dumper_spec.rb
                    rspec ./spec/bundle/brew_installer_spec.rb
                    rspec ./spec/bundle/brew_services_spec.rb

Failure/Error: require "codecov"

LoadError:
  cannot load such file -- version
# ./spec/spec_helper.rb:39:in `require'
# ./spec/spec_helper.rb:39:in `<top (required)>'
# ./spec/bundle/brew_dumper_spec.rb:3:in `require'

```

Repeated for all of our specs.

**Comment by thomasrockhu** [comment]
Thanks @colindean looking into it now
